# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Demux < Formula
  desc "Terminal multiplexer process manager"
  homepage "https://github.com/rtalexk/demux"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtalexk/demux/releases/download/v1.7.0/demux_darwin_amd64.tar.gz"
      sha256 "0ea796c6031e9ae72e59f257a8d20f18ff97ec3d58810e0bd765a5e6d98f8000"

      define_method(:install) do
        bin.install "demux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtalexk/demux/releases/download/v1.7.0/demux_darwin_arm64.tar.gz"
      sha256 "165915f83e8ac1e48fef5ca3a12e04ada3bd511d9cb5fb2c53a1736f133a67cb"

      define_method(:install) do
        bin.install "demux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtalexk/demux/releases/download/v1.7.0/demux_linux_amd64.tar.gz"
      sha256 "22f47576b8e2df80fb547bfd01d46b672fe61fa072687178e34cbc0705eca537"
      define_method(:install) do
        bin.install "demux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtalexk/demux/releases/download/v1.7.0/demux_linux_arm64.tar.gz"
      sha256 "fccd24eaa25fd0888938ef17a6f47636086e65b62cf8cca9ab35f06392f4629e"
      define_method(:install) do
        bin.install "demux"
      end
    end
  end

  test do
    system "#{bin}/demux", "--version"
  end
end
